expansion:
	cc \
	-Wall -Wextra \
	-g3 -O0 \
	expansion.c \
	../environ/*.c \
	-I../../includes \
	-I../../libft \
	../../libft/libft.a \
	-I../../ft_printf/includes \
	../../ft_printf/libftprintf.a \
	-o expansion

.PHONY:	expansion