env:
	cc -g3 -O0 -fsanitize=address \
	environ.c \
	env_lstiter_funcs.c \
	ft_unset.c \
	ft_env.c \
	ft_export.c \
	env_utils.c \
	-I../../libft ../../libft/libft.a \
	-I../../includes \
	-I../../ft_printf/include \
	../../ft_printf/libftprintf.a \
	-o env

.PHONY: env